services:
  - type: web
    name: job-board-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # This will prompt for MONGODB_URI during deployment
      - key: JWT_SECRET
        generateValue: true # This will generate a random JWT secret 